spring:

  # MVC Controller
  mvc:
    view:
      prefix: /
      suffix: .html
    hiddenmethod:
      filter:
        enabled: true

  main:
    allow-bean-definition-overriding: true 

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    
  jpa:
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #database-platform: org.hibernate.dialect.MariaDB53Dialect
    #database-platform: org.hibernate.dialect.SQLServer2012Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      format_sql: true
      ddl-auto: update

  datasource:  
    # mariadb
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/project_db?serverTimezone=Asia/Seoul&charaterEncoding=UTF-8
    #driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:3306/testsecurity?serverTimezone=Asia/Seoul&charaterEncoding=UTF-8
    # sqlServer
    # driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # url: jdbc:sqlserver://daeuserver2.iptime.org:1433;DatabaseName=UNICONS
    # username: UNICONS
    # password: UNICONS
    #postgresql
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://127.0.0.1:5432/tistory
    username: sangki
    password: sangki
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      encoding: UTF-8

mybatis:
  type-aliases-package: daeucna
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  
jwt:
  header: Authorization
  # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용
  # echo 'jsh-springboot-and-jwt-tutorial-this-is-for-generating-jwt-secretkey-base64'|base64
  secret: 4oCYc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXTigJkK
  token-validity-in-seconds: 60 
  refresh-token-validity-in-seconds: 86400 
  
#전체 로그 레벨 설정(기본 info)
logging:
  level:
    root: info 
    daeucna: debug

server:
  port: 80